[package]
name = "sqlite-clone"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sscanf = "0.4.1"

[dev-dependencies]
assert_cmd = "2.0.12"
predicates = "3.0.4"